-- Insert SQL Rules Here 
UPDATE Defines SET Value = '1' WHERE Name = 'SCIENCE_PER_POPULATION';
UPDATE Defines SET Value = '1' WHERE Name = 'QUEST_DISABLED_TOURISM';
UPDATE Defines SET Value = '1' WHERE Name = 'QUEST_DISABLED_ARCHAEOLOGY';
UPDATE Defines SET Value = '2' WHERE Name = 'MIN_CITY_RANGE';
